import hashlib
import importlib.util
import json
import os
from pathlib import Path

import pytest
import torch

from test_checkpoint_v2 import COMMIT, CONFIG, adam_fixture
from test_runtime_cli_contract import ROOT


def converter():
    path = ROOT / "tools/convert_legacy_checkpoint.py"
    spec = importlib.util.spec_from_file_location("operator_converter", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def legacy(tmp_path):
    model, optimizer = adam_fixture()
    path = tmp_path / "legacy.pt"
    torch.save(dict(model_state_dict=model.state_dict(), optimizer_state_dict=optimizer.state_dict(), iter=2), path)
    output = tmp_path / "output"
    output.mkdir()
    return path, output, hashlib.sha256(path.read_bytes()).hexdigest()


def convert(module, path, output, digest, **kwargs):
    return module.convert_legacy_checkpoint_once(path, output_root=output, approved_sha256=digest,
        producer_commit=COMMIT, resolved_config_sha256=CONFIG, **kwargs)


def test_operator_hash_empty_output_and_isolation_fail_closed(tmp_path, monkeypatch):
    module = converter()
    path, output, digest = legacy(tmp_path)
    with pytest.raises(ValueError, match="SHA"):
        convert(module, path, output, "f" * 64)
    assert not list(output.iterdir())
    (output / "existing").write_text("preserve")
    with pytest.raises(ValueError, match="empty"):
        convert(module, path, output, digest)
    assert (output / "existing").read_text() == "preserve"
    empty = tmp_path / "empty"
    empty.mkdir()
    monkeypatch.setattr(module, "BWRAP", "/missing/bwrap")
    with pytest.raises(ValueError, match="blocked"):
        convert(module, path, empty, digest)
    assert not list(empty.iterdir())


def test_real_os_sandbox_converts_and_external_loader_accepts(tmp_path):
    module = converter()
    path, output, digest = legacy(tmp_path)
    receipt = convert(module, path, output, digest)
    assert receipt["input_sha256"] == digest
    assert receipt["independent_safe_validation"] is True
    assert receipt["isolation"] == "bubblewrap-unshare-all"
    from rsl_rl.utils.checkpoint import load_checkpoint_v2
    loaded = load_checkpoint_v2(output / "checkpoint.manifest.json", artifact_root=output)
    assert loaded.iteration == 2
    assert loaded.optimizer_state_dict["state"]
    assert receipt["output_manifest_sha256"] == loaded.manifest_sha256
    assert json.loads((output / "conversion-receipt.json").read_text()) == receipt


def test_malicious_legacy_has_no_host_side_effect(tmp_path):
    module = converter()
    marker = tmp_path / "host-side-effect"
    class Exploit:
        def __reduce__(self):
            return os.system, ("touch " + str(marker),)
    path, output, _ = legacy(tmp_path)
    torch.save({"model_state_dict": {"evil": Exploit()}, "iter": 0}, path)
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    # Unsafe execution may only occur inside the sandbox. Its exit result is
    # plain data; all generated bytes are independently weights-only validated.
    receipt = convert(module, path, output, digest)
    assert receipt["independent_safe_validation"] is True
    assert not marker.exists()


def test_sandbox_resource_failure_does_not_publish_acceptance(tmp_path):
    module = converter()
    path, output, digest = legacy(tmp_path)
    with pytest.raises(ValueError, match="blocked|failed"):
        convert(module, path, output, digest, memory_bytes=32 * 1024 * 1024)
    assert not (output / "conversion-receipt.json").exists()


def test_no_legacy_converter_export_or_training_switch():
    import rsl_rl.utils
    assert not hasattr(rsl_rl.utils, "convert_legacy_checkpoint_once")
    for path in [ROOT / "training/rsl_rl/rsl_rl/runtime_preflight.py"]:
        assert "trust-legacy" not in path.read_text()


def test_actual_untrusted_probe_cannot_see_host_credentials_or_network(tmp_path, monkeypatch):
    monkeypatch.setenv("SEA_NAV_TEST_CREDENTIAL", "fixture-only-do-not-inherit")
    module = converter()
    class Probe:
        def __reduce__(self):
            code = "{'home':__import__('os').path.exists('/home'),'credential':__import__('os').environ.get('SEA_NAV_TEST_CREDENTIAL'),'interfaces':[n for i,n in __import__('socket').if_nameindex()]}"
            return eval, (code,)
    path, output, _ = legacy(tmp_path)
    torch.save({"model_state_dict": {"probe": Probe()}, "iter": 0}, path)
    receipt = convert(module, path, output, hashlib.sha256(path.read_bytes()).hexdigest())
    from rsl_rl.utils.checkpoint import load_checkpoint_v2
    probe = load_checkpoint_v2(output / "checkpoint.manifest.json", artifact_root=output).model_state_dict["probe"]
    assert probe == {"home": False, "credential": None, "interfaces": ["lo"]}
    assert receipt["resource_limits"]["memory_bytes"] == 4 * 1024**3


def test_pinned_input_survives_pathname_swap_before_sandbox(tmp_path, monkeypatch):
    module = converter()
    path, output, digest = legacy(tmp_path)
    original = module._sandbox_command
    def swap(settings, descriptors, *, validation):
        if not validation:
            path.rename(tmp_path / "retained-original")
            path.write_bytes(b"replacement path is not the approved input")
        return original(settings, descriptors, validation=validation)
    monkeypatch.setattr(module, "_sandbox_command", swap)
    assert convert(module, path, output, digest)["input_sha256"] == digest


def test_untrusted_infinite_work_is_terminated_without_receipt(tmp_path):
    module = converter()
    class Loop:
        def __reduce__(self):
            return eval, ("sum(iter(lambda:0,1))",)
    path, output, _ = legacy(tmp_path)
    torch.save({"model_state_dict": {"loop": Loop()}, "iter": 0}, path)
    with pytest.raises(ValueError, match="blocked or failed"):
        convert(module, path, output, hashlib.sha256(path.read_bytes()).hexdigest(), wall_seconds=2)
    assert not (output / "conversion-receipt.json").exists()


def test_independent_validator_rejects_hostile_worker_output(tmp_path, monkeypatch):
    module = converter()
    path, output, digest = legacy(tmp_path)
    marker = tmp_path / "validator-executed"
    class Exploit:
        def __reduce__(self):
            return os.system, ("touch " + str(marker),)
    original = module._sandbox_command
    def tamper(settings, descriptors, *, validation):
        if validation:
            manifest = output / "checkpoint.manifest.json"
            record = json.loads(manifest.read_text())
            artifact = output / record["artifact_path"]
            torch.save({"model_state_dict": {"evil": Exploit()}, "iteration": 2}, artifact)
            record.update(byte_size=artifact.stat().st_size, sha256=hashlib.sha256(artifact.read_bytes()).hexdigest())
            manifest.write_text(json.dumps(record))
        return original(settings, descriptors, validation=validation)
    monkeypatch.setattr(module, "_sandbox_command", tamper)
    with pytest.raises(ValueError, match="safe validator"):
        convert(module, path, output, digest)
    assert not marker.exists()
    assert not (output / "conversion-receipt.json").exists()


@pytest.mark.parametrize("kind", ["input", "output"])
def test_converter_rejects_symlink_targets(tmp_path, kind):
    module = converter()
    path, output, digest = legacy(tmp_path)
    link = tmp_path / "link"
    link.symlink_to(path if kind == "input" else output, target_is_directory=kind == "output")
    with pytest.raises(ValueError):
        convert(module, link if kind == "input" else path, link if kind == "output" else output, digest)
    assert not list(output.iterdir())


def test_approved_input_snapshot_is_stable_under_in_place_host_write(tmp_path, monkeypatch):
    module = converter()
    path, output, digest = legacy(tmp_path)
    old_inode = path.stat().st_ino
    original = module._sandbox_command
    def mutate(settings, descriptors, *, validation):
        if not validation:
            with path.open("r+b") as handle:
                handle.write(b"X" * path.stat().st_size)
            assert path.stat().st_ino == old_inode
        return original(settings, descriptors, validation=validation)
    monkeypatch.setattr(module, "_sandbox_command", mutate)
    receipt = convert(module, path, output, digest)
    assert receipt["input_sha256"] == digest and receipt["iteration"] == 2
