# SPDX-License-Identifier: MIT
"""Cross-platform method adaptation, not an original-paper or safety certificate."""

from .contracts import (
    ADAPTATION_ID,
    DASHGO_FORWARD_SENSOR_ENVELOPE_PROVENANCE,
    DASHGO_PLATFORM_PROVENANCE,
    DASHGO_REAL_LASERSCAN_RANGE_PROVENANCE,
    DASHGO_SIM_CAMERA_RANGE_PROVENANCE,
    ISAACLAB_CAMERA_DISTANCE_TO_CAMERA,
    ISAACLAB_CAMERA_DISTANCE_TO_IMAGE_PLANE,
    ROS_LASERSCAN_RADIAL_RANGE,
    RESULT_CLASSIFICATION,
    SAFETY_SEMANTICS,
    SEA_ACTION_STAGES,
    SEA_ALGORITHM_PROFILE,
    SEA_DASHGO_CANDIDATE_GEOMETRY,
    SEA_DASHGO_CANDIDATE_PROVENANCE,
    SEA_FRAME_FIELD_ORDER,
    SEA_PLATFORM_PROFILE,
    SEA_RESULT_CLASSIFICATION,
    SEA_RUNTIME_STACK,
    SEA_SOURCE_SEMANTICS,
    SEA_VALIDATION_IDENTITY,
    ActionSpec,
    DifferentialDrivePlatformSpec,
    EffectiveCommandEnvelopeSpec,
    ObservationSpec,
    RawSafetyObservationSpec,
    SeaNavActionSpec,
    SeaNavDashgoContractSet,
    SeaNavObservationSpec,
    sea_nav_dashgo_candidate_platform_spec,
    sea_nav_dashgo_raw_safety_spec,
)
from .observation import (
    BASE_ANGULAR_VELOCITY_SLICE,
    BASE_LINEAR_VELOCITY_SLICE,
    DELAYED_LOCAL_GOAL_SLICE,
    DELAYED_RANGES_SLICE,
    FRAME_COUNT,
    FRAME_DIM,
    INVALID_RAY_POLICY_PLACEHOLDER_M,
    MAX_SENSOR_AGE_S,
    POLICY_OBS_DIM,
    PREVIOUS_EXECUTED_COMMAND_SLICE,
    PROJECTED_GRAVITY_SLICE,
    RAW_SAFETY_REASON_ALL_INVALID,
    RAW_SAFETY_REASON_DOMAIN,
    RAW_SAFETY_REASON_NEGATIVE_AGE,
    RAW_SAFETY_REASON_NONFINITE,
    RAW_SAFETY_REASON_OK,
    RAW_SAFETY_REASON_STALE_AGE,
    RANGE_CHANNEL_CLAMP_MAX_M,
    RANGE_CHANNEL_CLAMP_MIN_M,
    SEA_RAY_COUNT,
    VALID_NO_HIT_RANGE_M,
    PolicyObservationHistory,
    RawSafetyStatus,
    SeaNavActorInput,
    build_policy_frame,
    policy_range_channels,
    policy_range_hold,
    raw_safety_row_status,
    sea_ray_angles_deg,
    sea_ray_angles_rad,
)
from .profiles import AblationProfile, resolve_ablation_profile
from .cbf import UnicycleLookaheadLSECBFLayer
from .losses import (
    PAPER_V1_ALPHA_MIN,
    PAPER_V1_LAMBDA_PI,
    PAPER_V1_LAMBDA_REG,
    PAPER_V1_LAMBDA_SHIELD,
    PAPER_V1_LAMBDA_V,
    paper_v1_lreg_loss,
    paper_v1_shield_loss,
)

__version__ = "0.4.0"
__all__ = [
    "ADAPTATION_ID", "DASHGO_FORWARD_SENSOR_ENVELOPE_PROVENANCE",
    "DASHGO_PLATFORM_PROVENANCE",
    "DASHGO_REAL_LASERSCAN_RANGE_PROVENANCE",
    "DASHGO_SIM_CAMERA_RANGE_PROVENANCE",
    "ISAACLAB_CAMERA_DISTANCE_TO_CAMERA",
    "ISAACLAB_CAMERA_DISTANCE_TO_IMAGE_PLANE", "ROS_LASERSCAN_RADIAL_RANGE",
    "RESULT_CLASSIFICATION",
    "SAFETY_SEMANTICS", "ActionSpec", "DifferentialDrivePlatformSpec",
    "EffectiveCommandEnvelopeSpec",
    "ObservationSpec", "RawSafetyObservationSpec", "AblationProfile",
    "resolve_ablation_profile", "UnicycleLookaheadLSECBFLayer",
    "PAPER_V1_ALPHA_MIN", "PAPER_V1_LAMBDA_PI", "PAPER_V1_LAMBDA_REG",
    "PAPER_V1_LAMBDA_SHIELD", "PAPER_V1_LAMBDA_V",
    "paper_v1_lreg_loss", "paper_v1_shield_loss",
    "SEA_ACTION_STAGES", "SEA_ALGORITHM_PROFILE", "SEA_DASHGO_CANDIDATE_GEOMETRY",
    "SEA_DASHGO_CANDIDATE_PROVENANCE", "SEA_FRAME_FIELD_ORDER",
    "SEA_PLATFORM_PROFILE", "SEA_RESULT_CLASSIFICATION", "SEA_RUNTIME_STACK",
    "SEA_SOURCE_SEMANTICS", "SEA_VALIDATION_IDENTITY",
    "SeaNavActionSpec", "SeaNavDashgoContractSet", "SeaNavObservationSpec",
    "sea_nav_dashgo_candidate_platform_spec", "sea_nav_dashgo_raw_safety_spec",
    "BASE_ANGULAR_VELOCITY_SLICE", "BASE_LINEAR_VELOCITY_SLICE",
    "DELAYED_LOCAL_GOAL_SLICE", "DELAYED_RANGES_SLICE", "FRAME_COUNT",
    "FRAME_DIM", "INVALID_RAY_POLICY_PLACEHOLDER_M", "MAX_SENSOR_AGE_S",
    "POLICY_OBS_DIM", "PREVIOUS_EXECUTED_COMMAND_SLICE",
    "PROJECTED_GRAVITY_SLICE",
    "RAW_SAFETY_REASON_ALL_INVALID", "RAW_SAFETY_REASON_DOMAIN",
    "RAW_SAFETY_REASON_NEGATIVE_AGE", "RAW_SAFETY_REASON_NONFINITE",
    "RAW_SAFETY_REASON_OK", "RAW_SAFETY_REASON_STALE_AGE",
    "RANGE_CHANNEL_CLAMP_MAX_M", "RANGE_CHANNEL_CLAMP_MIN_M", "SEA_RAY_COUNT",
    "VALID_NO_HIT_RANGE_M",
    "PolicyObservationHistory", "RawSafetyStatus", "SeaNavActorInput",
    "build_policy_frame", "policy_range_channels", "policy_range_hold",
    "raw_safety_row_status", "sea_ray_angles_deg", "sea_ray_angles_rad",
]
